<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Check error</name>
  <uuid>f2dc2101-b642-45e8-8420-4a739b93e081</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
     'ML model invocation' is in error 
then
    set decision to a new risk probabilities where
		the payment default is 0 , 
		the probability is 1 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
