<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>aplicar porcentaje</name>
  <uuid>844cfd60-cb24-4534-a114-a6988f9b4d4a</uuid>
  <locale>es_ES</locale>
  <definition><![CDATA[si
	'Porcentaje stock' es mayor o igual que 0 y menor que 101
entonces
	asignar a decisión 'Porcentaje stock' * la Unidades de 'Pedido Inicial' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
