<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>ffb6d87e-3884-4756-8acc-3ba38229b55f</uuid>
  <locale>es_ES</locale>
  <definition><![CDATA[asignar a decisión 0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
