<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default-value-setting</name>
  <uuid>15c8f66f-b62f-4e30-a744-9c58c0cd8c31</uuid>
  <locale>es_ES</locale>
  <definition><![CDATA[asignar a 'Cantidad semanal' un nuevo Cantidad Semanal en que
		la Semana 1 es 0,30, 
		la Semana 2 es 0,20, 
		la Semana 3 es 0,20, 
		la Semana 4 es 0,20 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
